### ISSUE TITLE
Union of more than three items fails

### ISSUE THREAD

**Issue by jesseduffield** [lerouxrgd/rsgen-avro#10] opened 2021-01-15 09:08 UTC
Schema:
```
{
  "type": "record",
  "name": "Contact",
  "namespace": "com.test",
  "fields": [
    {
      "name": "extra",
      "type": "map",
      "values" : [ "null", "string", "long", "double", "boolean" ]
    }
  ]
}
```
error:
```
Problem during code generation: Templating error: Didn't find schema Union(UnionSchema { schemas: [Null, String, Long, Double, Boolean], variant_index: {Boolean: 4, String: 1, Null: 0, Long: 2, Double: 3} }) in state GenState({})
```

This also fails with the following:
```
{
  "type": "record",
  "name": "Contact",
  "namespace": "com.test",
  "fields": [
    {
      "name": "extra",
      "type" : [ "null", "string", "long", "double", "boolean" ]
    }
  ]
}

```

If I reduce the values array to just "null" and "string" it works fine.

Let me know if you need any more info :)

**Comment by jesseduffield** [comment] 2021-01-15 09:12
I suspect this is because if both null and string are the only types, this easily maps to an Option<String>, but to add more types to the mix you would need to use a custom enum

**Comment by jesseduffield** [comment] 2021-01-15 09:17
...and I failed to read the README:
> Only union of the form ["null", "some-type"] are supported and treated as Option<_>.

Do you know how difficult it would be to add this functionality?

**Comment by lerouxrgd** [comment] 2021-01-15 10:24
I could give it a try, but I feel that it opens up the possibilities of many corner cases.

Also handling templating of default values for multi unions can get tricky I think (especially if some values are complex fields like record or array etc, which are potentially recursive).

**Comment by lerouxrgd** [comment] 2021-01-16 00:31
Actually the [spec] says that:

>  the type of the default value must match the first element of the union

So the default values should be doable.

Quickly giving it a try, I realize that the problem is that the generated enum doesn't have a clearly defined name.
While walking through the schema tree, when you reach a union's variant array of the enum, well you just have a list of types and no idea about what this list should be named.

**Comment by kuronyago** [comment] 2021-01-17 19:02
for the set ["null", "string", "long", "double", "boolean" ] it can be
```
enum Extra {
    Null,
    String(String),
    Long(i64),
    Double(f64),
    Boolean(bool),
}
```

**Comment by lerouxrgd** [comment] 2021-01-17 19:48
Yeah, but then what if you have `["null", "long", ["long", "boolean"]]` ? (there are many counter examples like this)
Sadly you cannot rely on the upper level field's name.

But I think I will try with auto generated names such as `UnionVarion1` etc (where the end user could change the string `UnionVariant`).

**Comment by kuronyago** [comment] 2021-01-17 20:02
with https://github.com/actgardner/gogen-avro input schema:
```
{
  "type": "record",
  "name": "AvroFileId",
  "fields": [
    {
      "name": "id",
      "type": [
        "string",
        {
          "type": "record",
          "name": "AvroShortUUID",
          "fields": [
            {
              "name": "mostBits",
              "type": "long"
            },
            {
              "name": "leastBits",
              "type": "long"
            }
          ]
        }
      ]
    }
  ]
}
```

result struct:
```
type AvroFileId struct {
	Id *UnionAvroShortUUIDString `json:"id"`
}
```

ugly name, but the way will probably work for any unnamed options

**Comment by lerouxrgd** [comment] 2021-01-28 21:04
@jesseduffield I added support for multi-valued unions on the branch `multi-union`.

I tested it with your example and it looks fine, generated code is as follows:

```rust
/// Auto-generated type for unnamed Avro union variants.
#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
pub enum UnionStringLongDoubleBoolean {
    String(String),
    Long(i64),
    Double(f64),
    Boolean(bool),
}

#[serde(default)]
#[derive(Debug, PartialEq, Clone, serde::Deserialize, serde::Serialize)]
pub struct Contact {
    pub extra: ::std::collections::HashMap<String, Option<UnionStringLongDoubleBoolean>>,
}

impl Default for Contact {
    fn default() -> Contact {
        Contact {
            extra: ::std::collections::HashMap::new(),
        }
    }
}
```

Could you let me know if that works for you ?

**Comment by jesseduffield** [comment] 2021-01-28 22:43
works for me!

**Comment by lerouxrgd** [comment] 2021-01-28 23:24
Thanks, this has been merged to master and released as `0.8.0`.

**Closed by lerouxrgd** 2021-01-28 23:24 UTC

**Comment by batconjurer** [comment] 2021-01-31 19:34
@lerouxrgd I am glad to see this issue has been resolved. I had thinking myself that auto-generated names were going to be unavoidable, so I made a crate a little while ago to try and standardize accessing variants (based on the C++ std::variant api) so that users weren't forced to interact with the generated names if they did not want to. It is a macro that can be easily added to the templates. It is [here](https://crates.io/crates/variant_access_traits) if you think it might be useful.

**Comment by lerouxrgd** [comment] 2021-01-31 20:16
Very interesting ! It could be added as an option to the union enum templates indeed.

The annoying thing here is to get a unique name for the unnamed Avro unions, `UnionStringLongDoubleBoolean` etc feels a bit cumbersome but I didn't find a better way...

**Comment by kuronyago** [comment] 2021-01-31 20:52
such names are a reason to think that your scheme smells bad
